version: '3.4'
services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Uelisson@4123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest-with-springboot-and-java-uelisson
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - uelisson-network
  rest-with-springboot-uelisson:
    build:
      context: ./rest-with-springboot-and-java-uelisson
      dockerfile: Dockerfile
    image: uelisson/rest-with-springboot-uelisson
    restart: always
    ports:
      - 80:80
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest-with-springboot-and-java-uelisson?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: Uelisson@4123
    depends_on:
      - db
    networks:
      - uelisson-network

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - uelisson-network
volumes:
  portainer_data:

networks:
  uelisson-network:
    driver: bridge
