name: Continuous Integration and Deployment with Docker

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
          cache-dependency-path: ./rest-with-springboot-and-java-uelisson/pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build application JAR
        working-directory: ./rest-with-springboot-and-java-uelisson
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker compose build

      - name: Tag and push Docker image to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-springboot-uelisson:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-springboot-uelisson:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-springboot-uelisson:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-springboot-uelisson:${{ github.run_id }}
