name: Continuos Integration and deployment docker with git

on:
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Build application .jar
      working-directory: ./rest-with-springboot-and-java-erudio/rest-with-springboot-and-java-uelisson
      run:  .\mvnw.cmd clean package #pode dar erro vou apenas deixar comentado pra consertar depois se der erro


    - name: Docker Compose Build
      working-directory: ./rest-with-springboot-and-java-erudio
      run: docker compose build

    - name: Push to DockerHub Container Registry
      run: | 
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-springboot-uelisson:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-springboot-uelisson:{{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-springboot-uelisson:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-springboot-uelisson:${{ github.run_id }}


